name: Setup GCP Authentication
description: 'Authenticate to Google Cloud using Workload Identity Federation (OIDC)'

# Purpose: Centralize GCP authentication logic using WIF/OIDC (no SA JSON keys)
# Category: Composite Action
# Usage: Eliminates duplicated auth steps across 5+ deployment workflows
# Created: 2025-11-12 (Enterprise CI Audit)

inputs:
  workload_identity_provider:
    description: 'GCP Workload Identity Provider (format: projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/POOL/providers/PROVIDER)'
    required: true
  
  service_account:
    description: 'GCP Service Account email (format: SA_NAME@PROJECT_ID.iam.gserviceaccount.com)'
    required: true
  
  project_id:
    description: 'GCP Project ID (optional, for setting default project)'
    required: false
    default: ''
  
  export_environment_variables:
    description: 'Export GCP environment variables (GCLOUD_PROJECT, GCP_PROJECT, GOOGLE_CLOUD_PROJECT)'
    required: false
    default: 'true'

outputs:
  project_id:
    description: 'Effective GCP project ID resolved by the action'
    value: ${{ steps.effective-project.outputs.project_id }}

runs:
  using: composite
  steps:
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@f112390a2df9932162083945e46d439060d66ec2  # v2.1.4
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}
        create_credentials_file: true
        export_environment_variables: ${{ inputs.export_environment_variables }}
        cleanup_credentials: true
        token_format: 'access_token'
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@f0990588f1e5b5af6827153b93673613abdc6ec7  # v2.1.1
      with:
        project_id: ${{ inputs.project_id }}
    
    - name: Determine effective project
      id: effective-project
      shell: bash
      run: |
        set -euo pipefail
        if [ -n "${{ inputs.project_id }}" ]; then
          gcloud config set project "${{ inputs.project_id }}" >/dev/null
          echo "project_id=${{ inputs.project_id }}" >> "$GITHUB_OUTPUT"
          exit 0
        fi
        
        if ! command -v gcloud >/dev/null 2>&1; then
          echo "gcloud CLI not found; cannot determine project_id" >&2
          echo "project_id=" >> "$GITHUB_OUTPUT"
          exit 1
        fi
        
        ACTIVE_ACCOUNT="$(gcloud auth list --filter=status:ACTIVE --format='value(account)' | tr -d '\n')"
        if [ -z "$ACTIVE_ACCOUNT" ]; then
          echo "No active gcloud account; authentication may have failed" >&2
          echo "project_id=" >> "$GITHUB_OUTPUT"
          exit 1
        fi
        
        PROJECT_ID="$(gcloud config get-value project 2>/dev/null || true)"
        if [ -z "$PROJECT_ID" ] || [ "$PROJECT_ID" = "(unset)" ]; then
          echo "project_id=" >> "$GITHUB_OUTPUT"
          echo "No default project set in gcloud config; pass 'project_id' input to this action." >&2
          exit 1
        fi
        
        echo "project_id=$PROJECT_ID" >> "$GITHUB_OUTPUT"
    
    - name: Verify authentication
      shell: bash
      run: |
        echo "✅ Authenticated as:"
        gcloud auth list --filter=status:ACTIVE --format="value(account)"
        
        EFFECTIVE_PROJECT="${{ steps.effective-project.outputs.project_id }}"
        if [ -n "$EFFECTIVE_PROJECT" ]; then
          echo "📍 Default project: $EFFECTIVE_PROJECT"
        else
          echo "📍 Default project: (not set)"
        fi
