name: Claude PR Assistant (v2)

on:
  workflow_call:
    inputs:
      pr_number:
        description: 'PR number (optional, for manual wrapper triggers)'
        type: number
        required: false
      trigger_labels:
        type: string
        required: false
        default: "ai-review"
      skip_labels:
        type: string
        required: false
        default: "no-ai"
      model:
        type: string
        required: false
        default: "claude-3-5-sonnet-20241022"
      temperature:
        type: number
        required: false
        default: 0.2
      mode:
        type: string
        required: false
        default: "suggest" # suggest | apply-suggestions
      max_output_chars:
        type: number
        required: false
        default: 4000
      max_diff_lines:
        type: number
        required: false
        default: 8000
    secrets:
      ANTHROPIC_API_KEY:
        required: false
  
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number (required for manual trigger)'
        type: number
        required: true
      model:
        description: 'AI model'
        type: choice
        required: false
        default: 'claude-3-5-sonnet-20241022'
        options:
          - claude-3-5-sonnet-20241022
          - claude-3-opus-20240229
          - claude-3-sonnet-20240229
      temperature:
        description: 'Temperature (0.0-1.0, lower = more conservative)'
        type: number
        required: false
        default: 0.2
      mode:
        description: 'Review mode'
        type: choice
        required: false
        default: 'suggest'
        options:
          - suggest
          - apply-suggestions
      max_output_chars:
        description: 'Max output length'
        type: number
        required: false
        default: 4000
      max_diff_lines:
        description: 'Max diff lines to analyze'
        type: number
        required: false
        default: 8000

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  ai_review:
    runs-on: ubuntu-latest
    concurrency:
      group: claude-pr-v2-${{ github.event.pull_request.number || inputs.pr_number || github.run_id }}
      cancel-in-progress: true
    
    env:
      PR_NUMBER: ${{ github.event.pull_request.number || inputs.pr_number }}
    
    steps:
      - name: Validate PR context
        run: |
          if [ -z "$PR_NUMBER" ]; then
            echo "❌ PR number missing. Use workflow_dispatch with pr_number input or trigger from PR event."
            exit 1
          fi
          echo "✅ Processing PR #$PR_NUMBER"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Label gates
        id: gates
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const tri = (s)=> (s||'').split(',').map(x=>x.trim()).filter(Boolean);
            const trig = tri('${{ inputs.trigger_labels }}');
            const skip = tri('${{ inputs.skip_labels }}');
            const labels = (context.payload.pull_request?.labels||[]).map(l=>l.name);
            const hasTrig = trig.length===0 || trig.some(t=>labels.includes(t));
            const hasSkip = skip.some(s=>labels.includes(s));
            core.setOutput('run', (hasTrig && !hasSkip) ? 'true':'false');

      - name: Stop if gated off
        if: github.event_name == 'pull_request' && steps.gates.outputs.run != 'true'
        run: echo "Gated off by labels"; exit 0

      - name: Fetch PR diff (truncated)
        id: diff
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          gh pr diff "$PR_NUMBER" --patch > pr.diff || true
          head -n "${{ inputs.max_diff_lines }}" pr.diff > pr.trunc.diff || true

      - name: Fetch PR metadata
        id: pr_info
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          PR_TITLE=$(gh pr view "$PR_NUMBER" --json title -q .title)
          PR_BODY=$(gh pr view "$PR_NUMBER" --json body -q .body)
          echo "title=$PR_TITLE" >> $GITHUB_OUTPUT
          echo "body=$PR_BODY" >> $GITHUB_OUTPUT
      
      - name: Build prompt
        run: |
          set -euo pipefail
          mkdir -p .tmp
          printf "%s" "${{ steps.pr_info.outputs.title }}" | head -c 300 > .tmp/title.txt
          printf "%s" "${{ steps.pr_info.outputs.body }}"  | head -c 2000 > .tmp/body.txt
          {
            echo "You are a helpful, cautious code reviewer."
            echo "Rules: no secrets; least-privilege; safe shell; no destructive infra."
            echo
            echo "PR title:"; cat .tmp/title.txt
            echo; echo "PR body:"; cat .tmp/body.txt
            echo; echo "PR diff:"; echo '```'; cat pr.trunc.diff; echo '```'
          } > .tmp/prompt.txt

      - name: Call Anthropic
        id: llm
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          set -euo pipefail
          if [ -z "${ANTHROPIC_API_KEY:-}" ]; then
            printf "LLM not configured.\n" > .tmp/review.md
            exit 0
          fi
          payload=$(jq -n \
            --arg model "${{ inputs.model }}" \
            --arg prompt "$(cat .tmp/prompt.txt)" \
            '{model:$model,max_tokens:1800,messages:[{role:"user",content:$prompt}],temperature:0.2}')
          resp=$(curl -sS https://api.anthropic.com/v1/messages \
            -H "content-type: application/json" \
            -H "x-api-key: ${ANTHROPIC_API_KEY}" \
            -H "anthropic-version: 2023-06-01" \
            -d "$payload")
          echo "$resp" | jq -r '.content[0].text // ""' | head -c "${{ inputs.max_output_chars }}" > .tmp/review.md

      - name: Create/update comment (idempotent)
        if: ${{ inputs.mode == 'suggest' || github.event.inputs.mode == 'suggest' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ env.PR_NUMBER }}
          body-path: .tmp/review.md
          edit-mode: replace
          reactions: hooray

      - name: Convert review to suggestions (placeholder)
        if: ${{ inputs.mode == 'apply-suggestions' }}
        run: |
          echo "Apply-suggestions placeholder: convert .tmp/review.md into GH review suggestions"
