name: Claude PR Assistant (v2)

on:
  workflow_call:
    inputs:
      trigger_labels:
        type: string
        required: false
        default: "ai-review"
      skip_labels:
        type: string
        required: false
        default: "no-ai"
      model:
        type: string
        required: false
        default: "claude-3-5-sonnet-20241022"
      temperature:
        type: number
        required: false
        default: 0.2
      mode:
        type: string
        required: false
        default: "suggest" # suggest | apply-suggestions
      max_output_chars:
        type: number
        required: false
        default: 4000
      max_diff_lines:
        type: number
        required: false
        default: 8000
    secrets:
      ANTHROPIC_API_KEY:
        required: false

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  ai_review:
    runs-on: ubuntu-latest
    concurrency:
      group: claude-pr-v2-${{ github.event.pull_request.number || github.run_id }}
      cancel-in-progress: true
    steps:
      - name: Ensure pull_request context
        if: ${{ github.event_name != 'pull_request' }}
        run: echo "Only pull_request supported"; exit 0

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Label gates
        id: gates
        uses: actions/github-script@v7
        with:
          script: |
            const tri = (s)=> (s||'').split(',').map(x=>x.trim()).filter(Boolean);
            const trig = tri('${{ inputs.trigger_labels }}');
            const skip = tri('${{ inputs.skip_labels }}');
            const labels = (context.payload.pull_request?.labels||[]).map(l=>l.name);
            const hasTrig = trig.length===0 || trig.some(t=>labels.includes(t));
            const hasSkip = skip.some(s=>labels.includes(s));
            core.setOutput('run', (hasTrig && !hasSkip) ? 'true':'false');

      - name: Stop if gated off
        if: steps.gates.outputs.run != 'true'
        run: echo "Gated off"; exit 0

      - name: Fetch PR diff (truncated)
        id: diff
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          gh pr diff "${{ github.event.pull_request.number }}" --patch > pr.diff || true
          head -n "${{ inputs.max_diff_lines }}" pr.diff > pr.trunc.diff || true

      - name: Build prompt
        run: |
          set -euo pipefail
          mkdir -p .tmp
          printf "%s" "${{ github.event.pull_request.title }}" | head -c 300 > .tmp/title.txt
          printf "%s" "${{ github.event.pull_request.body }}"  | head -c 2000 > .tmp/body.txt
          {
            echo "You are a helpful, cautious code reviewer."
            echo "Rules: no secrets; least-privilege; safe shell; no destructive infra."
            echo
            echo "PR title:"; cat .tmp/title.txt
            echo; echo "PR body:"; cat .tmp/body.txt
            echo; echo "PR diff:"; echo '```'; cat pr.trunc.diff; echo '```'
          } > .tmp/prompt.txt

      - name: Call Anthropic
        id: llm
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          set -euo pipefail
          if [ -z "${ANTHROPIC_API_KEY:-}" ]; then
            printf "LLM not configured.\n" > .tmp/review.md
            exit 0
          fi
          payload=$(jq -n \
            --arg model "${{ inputs.model }}" \
            --arg prompt "$(cat .tmp/prompt.txt)" \
            '{model:$model,max_tokens:1800,messages:[{role:"user",content:$prompt}],temperature:0.2}')
          resp=$(curl -sS https://api.anthropic.com/v1/messages \
            -H "content-type: application/json" \
            -H "x-api-key: ${ANTHROPIC_API_KEY}" \
            -H "anthropic-version: 2023-06-01" \
            -d "$payload")
          echo "$resp" | jq -r '.content[0].text // ""' | head -c "${{ inputs.max_output_chars }}" > .tmp/review.md

      - name: Create/update comment (idempotent)
        if: ${{ inputs.mode == 'suggest' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-path: .tmp/review.md
          edit-mode: replace
          reactions: hooray

      - name: Convert review to suggestions (placeholder)
        if: ${{ inputs.mode == 'apply-suggestions' }}
        run: |
          echo "Apply-suggestions placeholder: convert .tmp/review.md into GH review suggestions"
